### ISSUE TITLE
Vellamo workload fails to run

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#590]
For the first run, vellamo workload fails to run. Apparently the script is expecting vellamo to be already installed. If I first install it 'adb install com.quicinc.vellamo.3.2.6.apk' and then run the workload, it works.

WA version: 2.6.0

INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     Running workload 1 vellamo (iteration 1)
INFO            Setting up
INFO            Skipping the rest of the iterations for this spec.
ERROR    Error while running vellamo
ERROR    CalledProcessErrorWithStderr("Command 'adb -s 91AD00701767961 uninstall com.quicinc.vellamo' returned non-zero exit status 255
ERROR    STDOUT: None
ERROR    STDERR:
ERROR    Exception occurred while executing:
ERROR    java.lang.IllegalArgumentException: Unknown package: com.quicinc.vellamo
ERROR           at com.android.server.pm.Settings.isOrphaned(Settings.java:4409)
ERROR           at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:22228)
ERROR           at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:19147)
ERROR           at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:745)
ERROR           at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:935)
ERROR           at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
ERROR           at android.os.ShellCommand.exec(ShellCommand.java:96)
ERROR           at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22528)
ERROR           at android.os.Binder.shellCommand(Binder.java:616)
ERROR           at android.os.Binder.onTransact(Binder.java:514)
ERROR           at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2660)
ERROR           at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3774)
ERROR           at android.os.Binder.execTransact(Binder.java:711)
ERROR    ")
ERROR    Got:
ERROR    None
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/core/execution.py", line 752, in _handle_errors
ERROR        yield
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/core/execution.py", line 624, in _run_job
ERROR        self._run_workload_iteration(spec.workload)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/core/execution.py", line 679, in _run_workload_iteration
ERROR        workload.setup(self.context)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/workloads/vellamo/__init__.py", line 85, in setup
ERROR        super(Vellamo, self).setup(context)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/common/android/workload.py", line 581, in setup
ERROR        AndroidBenchmark.setup(self, context)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/common/android/workload.py", line 263, in setup
ERROR        self.prefer_host_apk(context, host_version, target_version)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/common/android/workload.py", line 320, in prefer_host_apk
ERROR        self.install_apk(context, replace=True)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/common/android/workload.py", line 401, in install_apk
ERROR        self.device.uninstall(self.package)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/common/android/device.py", line 431, in uninstall
ERROR        adb_command(self.adb_name, "uninstall {}".format(package), timeout=self.default_timeout)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/android.py", line 405, in adb_command
ERROR        output, _ = check_output(full_command, timeout, shell=True)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/misc.py", line 138, in check_output
ERROR        raise CalledProcessErrorWithStderr(retcode, command, output=output, error=error)
ERROR    
INFO     Job status was FAILED. Retrying...
INFO     Skipping workload 1 vellamo (iteration 2)
INFO     Finalizing workloads
INFO     Finalizing.
INFO     Processing overall results
INFO     Status available in /var/www/wa_output/hikey-4.9-android-8.0.0_r4-4360-gb3a770e256f9/status.txt
INFO     Done.
INFO     Run duration: 3 seconds
INFO     Ran a total of 2 iterations: 1 FAILED, 1 SKIPPED
INFO     Results can be found in /var/www/wa_output/hikey-4.9-android-8.0.0_r4-4360-gb3a770e256f9
WARNING  There were errors during execution.
WARNING  Please see /var/www/wa_output/hikey-4.9-android-8.0.0_r4-4360-gb3a770e256f9/run.log

**Comment by marcbonnici** [comment]
Hello,

I think this particular problem may have been resolved. Would you be able to install the latest version of WA from GitHub and see if that fixes the issue?

**Comment by dlezcano** [comment]
Thanks for your quick answer. I give it a try.
Side question: usually what is the release period ? I prefer to stick to delivered rather than dev component.

**Comment by dlezcano** [comment]
I tried but the issue is still there. May be I missed something. I uninstalled wlauto with 'sudo -H pip uninstall wlauto' which happened without error. Then following the instructions in the documentation I installed the git version with 'sudo -H pip install ./workload_automation' without error.
Then I ran the vellamo workload again but it failed with the same error.
Note: I have a version 2.6.0 showed while I was expecting a different version name for the dev, eg. 2.6.0+ or whatever. So I not sure I'm actually using the right wlauto version.

**Comment by marcbonnici** [comment]
Our release period is currently rather infrequent, and the version on GitHub is currently significantly more update to date however most work done on WA2 at the moment is bug fixes so it should be quite stable.

The version name will actually be the same for the release version and the GitHub version, so you can expect to see 2.6.0. However I managed to reproduce your issue with the default pip installed version but not the GitHub version.
The steps you've taken to switch versions should have worked however to be sure could you try uninstalling wa again and then running `python -c "import wlauto"` in a shell to check it throws an error and that it has uninstalled correctly?

**Comment by dlezcano** [comment]
So the 'master' branch contains bug fixes only ?

**Comment by dlezcano** [comment]
sudo -H pip uninstall wlauto
python -c "import wlauto"
does *not* throw an error

**Comment by marcbonnici** [comment]
It is not necessarily only bug fixes however most of the development work is taking place on the next branch now.

Ah ok, so there must be another version of WA still installed on the system somewhere.

Can you open an interactive Python console and run `import wlauto` and then print `wlauto.__file__`?
This should give you the full location of the package, then can you `rm -rf` the `wlauto` folder and the repeat the previous test?

**Comment by dlezcano** [comment]
I followed the instructions but now I have the error:
INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     Running workload 1 vellamo (iteration 1)
INFO            Setting up
INFO            Skipping the rest of the iterations for this spec.
ERROR    Error while running vellamo:
ERROR           Could not find APK for 'vellamo' on the host or target device
INFO     Job status was FAILED. Retrying...

**Comment by dlezcano** [comment]
But I have:
~/.workload_automation/dependencies/vellamo/com.quicinc.vellamo.3.2.6.apk

**Comment by marcbonnici** [comment]
The vellamo workload will look for one of the following versions to install from the host `2.0.3`, `3.0` or `3.2.4`, defaulting to `3.2.4`. Could you drop that specific version in the vellamo dependencies folder?

**Comment by dlezcano** [comment]
I can confirm the problem is fixed:
 - uninstalled vellamo manually (adb uninstall com.quicinc.vellamo)
 - copied com.quicinc.vellamo.3.2.4.apk to ~/.workload_automation/dependencies/vellamo
 - ran the workload: wa run -f -d /var/www/wa_output/$(cd $ANDROID_KERNEL && git describe --abbrev=12) vellamo

INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     Running workload 1 vellamo (iteration 1)
INFO            Setting up
INFO            Executing
INFO            Processing result
INFO            Tearing down
INFO     Finalizing workloads
INFO     Finalizing.
INFO     Processing overall results
INFO     Status available in /var/www/wa_output/hikey-4.9-android-8.0.0_r4-4360-gb3a770e256f9/status.txt
INFO     Done.
INFO     Run duration: 7 minutes 17 seconds
INFO     Ran a total of 1 iterations: 1 OK
INFO     Results can be found in /var/www/wa_output/hikey-4.9-android-8.0.0_r4-4360-gb3a770e256f9

Thanks for your help !
